-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1
-- Tiempo de generación: 21-09-2023 a las 06:33:19
-- Versión del servidor: 10.4.24-MariaDB
-- Versión de PHP: 7.4.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `generadorqr`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `guia`
--

CREATE TABLE `guia` (
  `id` int(100) NOT NULL,
  `nombre_equipo` longtext NOT NULL,
  `descripcion` longtext NOT NULL,
  `advertencias` longtext NOT NULL,
  `nota_partes` longtext NOT NULL,
  `nota_funcionamiento` longtext NOT NULL,
  `limpieza` longtext NOT NULL,
  `nota_limpieza` longtext NOT NULL,
  `estado` int(10) NOT NULL,
  `fecha_creacion` datetime DEFAULT NULL,
  `url_guia` varchar(300) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `guia`
--

INSERT INTO `guia` (`id`, `nombre_equipo`, `descripcion`, `advertencias`, `nota_partes`, `nota_funcionamiento`, `limpieza`, `nota_limpieza`, `estado`, `fecha_creacion`, `url_guia`) VALUES
(1, 'BOMBA DE INFUSIÓN EVO-IQ', 'Este equipo es un sistema diseñado para el proceso de administración de medicamentos al paciente, diseñado para ser usado en una variedad de entornos de atención a pacientes que incluyen adultos, pediátricos y neonatales.', 'Por seguridad del paciente tener siempre claro la dosis requerida por el paciente y mantener las bombas conectadas a la red eléctrica.', 'Para realizar la instalación el sistema debe estar purgado adecuadamente.1 Abra la puertas subiendo la palanca (número 8 del ítem I).2 Tenga en cuenta la dirección de flujo del sistema (Figura 1).3 Para acoplar el sistema primero debe cerrar la pinza.4 Iniciar introduciendo la pienza como muesta el numeral 1 de la figura 3.5 Tiemple delicadamente el sistema para acoplarlo de los extremos como muestra el numeral 2 de la figura 3.6 Termine de ajustar el sistema en como muestra el numeral 3 y 4 de la figura 3.', 'Presione el boton para detener la infusión (número 11 del ítem I). Presione el clip gris como muestra la figura 1. Primero retire el equipo de los extremos y siga retirando el equipo de cada enganche. Cierre la puerta, levantandola y empujando la palanca (número 8 del ítem I).', 'Aplique el desinfectante a usar de manera moderada a la toalla. Pase la toalla por las superficies del equipo y accesorios.', 'Para evitar daños en el equipo al momendo de la desinfección tenga en cuenta que:No debe apliquar el desinfectante directamente al equipo o accesorios.No debe dejar excesos de desinfectante en el equipo o accesorios.', 0, '2023-09-20 00:00:00', NULL),
(2, 'BOMBA DE NUTRICIÓN ENTERAL  COVIDIEN KANGAROO', 'ANTES DE ENCENDER EL EQUIPO\r\nVerifique que la clavija del cable AC tiene tres pines (fase, neutro y tierra). De no ser así informe al área de equipo médico.\r\n', 'Es necesario tener conectada la bomba al toma de poder, para mantener la carga de la batería.\r\n', '--', '--', 'Aplique el desinfectante a usar de manera moderada a la toalla.\r\nPase la toalla por las superficies del equipo y accesorios.\r\n', 'Para evitar daños en el equipo al momendo de la desinfección tenga en cuenta que:\r\nNo debe apliquar el desinfectante directamente al equipo o accesorios.\r\nNo debe dejar excesos de desinfectante en el equipo o accesorios.\r\n', 0, '2023-09-20 09:22:25', NULL),
(3, 'DESFIBRILADOR BENEHEART D3\r\n', 'El equipo es un deibrilador portátil que proporciona 4 modos de funcionamiento: Monitor, Desf. Manual, DEA y Marcap. Dentro de estas funciones el equipo podrá realizar desfibrilacón externa, cardioversión sincronizada, desfibrilación semiautomática y monitorización de ECG, SpO2, FP y Resp.', 'El equipo administra hasta 360 J de energía eléctrica, esta energía eléctrica puede provocar lesiones graves o la muerte. Mantenga la distancia con dispositivos metálicos conectados a él durante la desfibrilación.', '--', '--', 'Aplique el desinfectante a usar de manera moderada a la toalla.\r\nPase la toalla por las superficies del equipo y accesorios.\r\n', 'Para evitar daños en el equipo al momendo de la desinfección tenga en cuenta que:\r\nNo debe apliquar el desinfectante directamente al equipo o accesorios.\r\nNo debe dejar excesos de desinfectante en el equipo o accesorios.\r\n', 0, '2023-09-20 09:23:44', NULL),
(4, 'ELECTROCARDIÓGRAFO  DE 12 DERIVACIONES - MAC 600\r\n', 'El electrocardiografo está indicado para adquirir, analizar, presentar en pantalla y registrar información electrocardiográfica.\r\n', 'El movimiento del paciente puede generar un ruido excesivo y afectar a la calidad del trazado ECG y del análisis que realiza el aparato. Limpie y desinfecte los electrodos después del uso con el paciente.\r\n', '--', '--', 'Aplique el desinfectante a usar de manera moderada a la toalla.\r\nPase la toalla por las superficies del equipo y accesorios.\r\n', 'Para evitar daños en el equipo al momendo de la desinfección tenga en cuenta que:\r\nNo debe apliquar el desinfectante directamente al equipo o accesorios.\r\nNo debe dejar excesos de desinfectante en el equipo o accesorios.\r\n', 0, '2023-09-20 09:25:55', NULL),
(5, 'GLUCÓMETRO ROCHE ACCUCHECK INFORM II\r\n', 'El dispositivo es para uso diagnóstico in vitro en la determinación cuantitativa de los niveles de glucemia en muestras de sangre venosa, capilar, arterial y neonatal.\r\n', 'El equipo trabaja con baterías que deben mantenerse cargando en la estación base, la cual debe ir siempre conectada a la red eléctrica.\r\n', '--', '--', 'Aplique el desinfectante a usar de manera moderada a la toalla.\r\nPase la toalla por las superficies del equipo y accesorios.\r\n', 'El equipo cuenta con una memoria para almacenar 1000 estudios. Al agotarse la memoria mostrara una alarma de “memoria llena”, en este caso se debe realizar la transferencia de datos en la base de carga del glucometro. Para ello:\r\nPosicionar el glucometro en la base.\r\nEsperar que aparezca el mensaje transfiriendo datos. El tiempo minimo de descarga  es de 15 minutos.\r\nSi al retirar el glucometro de la base no aparece la alarma, el dispositivo ya esta en optimas condiciones de funcionamiento.\r\n\r\nPara evitar daños en el equipo al momendo de la desinfección tenga en cuenta que:\r\nNo debe apliquar el desinfectante directamente al equipo o accesorios.\r\nNo debe dejar excesos de desinfectante en el equipo o accesorios.\r\n', 0, '2023-09-20 09:27:13', NULL),
(6, 'LÁMPARA CIALÍTICA TRILUX', 'El equipo es una luminaria médica para el uso en las salas de un hospital, se usa parala iluminación local del cuerpo del paciente, para poder reconocer y tratar enfermedades, heridas y lesiones.\r\n', 'Verifique que la lámpara no esté contaminada con fluidos y que el panel de control esté funcionando completamente.\r\n', '--', '--', 'Aplique el desinfectante a usar de manera moderada a la toalla.\r\nPase la toalla por las superficies del equipo y accesorios.\r\n', 'Para evitar daños en el equipo al momendo de la desinfección tenga en cuenta que:\r\nNo debe apliquar el desinfectante directamente al equipo o accesorios.\r\nNo debe dejar excesos de desinfectante en el equipo o accesorios.\r\n', 0, '2023-09-20 09:30:28', NULL),
(7, 'MÁQUINA DE ANESTESIA AVANCE CS2', 'La máquina de anestesia combina un sistema avanzado para la administración de anestesia, monitorización de pacientes y gestión de información. Este sistema permite integrar la ventilación, el suministro de gas y la monitorización de gases en la pantalla.\r\n', 'Mantenga el equipo conectado a la red electrica para preservar la batería. No utilizar el sistema en ambientes con nivel de oxígeno superior a 25%.\r\n', '--', '--', 'Aplique el desinfectante a usar de manera moderada a la toalla.\r\nPase la toalla por las superficies del equipo y accesorios.\r\n', 'Para evitar daños en el equipo al momendo de la desinfección tenga en cuenta que:\r\nNo debe apliquar el desinfectante directamente al equipo o accesorios.\r\nNo debe dejar excesos de desinfectante en el equipo o accesorios.\r\n', 0, '2023-09-20 09:31:51', NULL),
(8, 'MÁQUINA DE ANESTESIA CARESTATION 620A1', 'La máquina de anestesia combina un sistema avanzado para la administración de anestesia, monitorización de pacientes y gestión de información. Este sistema permite integrar la ventilación, el suministro de gas y la monitorización de gases en la pantalla.', 'Por seguridad del paciente el equipo debe estar conectado a tierra. Consulte con el Ingeniero Biomédico.', '--', '--', 'Aplique el desinfectante a usar de manera moderada a la toalla.\r\nPase la toalla por las superficies del equipo y accesorios.\r\n', 'Para evitar daños en el equipo al momendo de la desinfección tenga en cuenta que:\r\nNo debe apliquar el desinfectante directamente al equipo o accesorios.\r\nNo debe dejar excesos de desinfectante en el equipo o accesorios.\r\n', 0, '2023-09-20 09:33:27', NULL),
(9, 'MESA DE CIRUGÍA CMAX3-DRIVE 3082', 'Este equipo cuenta con varias secciones que se mueven mediante un mecanismo electrohidráulico y disponen de una transferencia motorizada.', 'Por seguridad del paciente el equipo debe estar conectado a tierra. Consulte con el Ingeniero Biomédico.', '--', '--', 'Aplique el desinfectante a usar de manera moderada a la toalla.\r\nPase la toalla por las superficies del equipo y accesorios.\r\n', 'Para evitar daños en el equipo al momendo de la desinfección tenga en cuenta que:\r\nNo debe apliquar el desinfectante directamente al equipo o accesorios.\r\nNo debe dejar excesos de desinfectante en el equipo o accesorios.', 0, '2023-09-20 09:57:11', NULL),
(10, 'MONITOR DE SIGNOS VITALES - B125', 'Este equipo es una unidad multiparamétrica para la supervisión, el registro y la generación de alarmas de múltipametros fisiológicos de pacientes adultos, pediátricos y neonatales.', 'Este equipo está diseñado para ser usado con un solo paciente, antes de usarlo verifique el buen estado del equipo y sus accesorios. No use el equipo con agentes anestésicos inflamables.\r\n', '--', '--', 'Aplique el desinfectante a usar de manera moderada a la toalla.\r\nPase la toalla por las superficies del equipo y accesorios.', 'Para evitar daños en el equipo al momendo de la desinfección tenga en cuenta que:\r\nNo debe apliquar el desinfectante directamente al equipo o accesorios.\r\nNo debe dejar excesos de desinfectante en el equipo o accesorios.', 0, '2023-09-20 09:59:34', NULL),
(11, 'MONITOR DE SIGNOS VITALES CARESCOPE B450 - B650\r\n', 'Este equipo está diseñado para la utilización de un solo paciente. La utilización de este equipo para monitorizar diferentes parámetros en distintos pacientes al mismo tiempo, pone en risgo la exactitud de los datos adquiridos\r\n', 'Este equipo está diseñado para ser usado con un solo paciente, antes de usarlo verifique el buen estado del equipo y sus accesorios. No use el equipo con agentes anestésicos inflamables.\r\n', '--', '--', 'Aplique el desinfectante a usar de manera moderada a la toalla.\r\nPase la toalla por las superficies del equipo y accesorios.\r\n', 'Para evitar daños en el equipo al momendo de la desinfección tenga en cuenta que:\r\nNo debe apliquar el desinfectante directamente al equipo o accesorios.\r\nNo debe dejar excesos de desinfectante en el equipo o accesorios.\r\n', 0, '2023-09-20 10:06:37', NULL),
(12, 'MONITOR DE SIGNOS VITALES - iMEC 8 - iMEC 12', 'Los monitores iMEC están diseñados para monitorizar, visualizar, almacenar y transferir diversos parámetros, como ECG, frecuencia cardiaca, respiración, temperatura, saturación de oxígeno y pulso, frecuencia del pulso, presión sanguínea no invasiva y presión sanguínea invasiva (iMEC12).', 'Este equipo está diseñado para ser usado con un solo paciente, antes de usarlo verifique el buen estado del equipo y sus accesorios. No use el equipo con agentes anestésicos inflamables.', '--', '--', 'Aplique el desinfectante a usar de manera moderada a la toalla.\r\nPase la toalla por las superficies del equipo y accesorios.\r\n', 'Para evitar daños en el equipo al momendo de la desinfección tenga en cuenta que:\r\nNo debe apliquar el desinfectante directamente al equipo o accesorios.\r\nNo debe dejar excesos de desinfectante en el equipo o accesorios.\r\n', 0, '2023-09-20 10:13:48', NULL),
(13, 'MONITOR DE SIGNOS VITALES - V100\r\n', 'El monitor CARESCAPE V100, es un sistema portátil, pequeño y fácil de usar. Permite la monitorización de parámetros como la presión sanguínea sistólica y diastólica, presión arterial media, la frecuencia de pulso, el grado de saturación de oxígeno y la temperatura.\r\n', 'Este equipo está diseñado para ser usado con un solo paciente, antes de usarlo verifique el buen estado del equipo y sus accesorios. No use el equipo con agentes anestésicos inflamables.\r\n', '--', '--', 'Aplique el desinfectante a usar de manera moderada a la toalla.\r\nPase la toalla por las superficies del equipo y accesorios.', 'Para evitar daños en el equipo al momendo de la desinfección tenga en cuenta que:\r\nNo debe apliquar el desinfectante directamente al equipo o accesorios.\r\nNo debe dejar excesos de desinfectante en el equipo o accesorios.\r\n', 0, '2023-09-20 10:15:15', NULL),
(14, 'VENTILADOR MECÁNICO - CARESCAPE R860', 'El ventilador CARESCAPE R860 está diseñado para proporcionar ventilación mecánica o auxiliar a pacientes neonatales, pediátricos y adultos con un peso de 0,25 kg o superior. Incluye monitorización integrada de FiO2, flujo, volumen y presión en vías aéreas.\r\n', 'Este ventilador solo debe ser usado por el personal médico autorizado. Este ventilador no está previsto para utilizarse en traslados.\r\n', '--', '--', 'Aplique el desinfectante a usar de manera moderada a la toalla.\r\nPase la toalla por las superficies del equipo y accesorios.\r\n', 'Para evitar daños en el equipo al momendo de la desinfección tenga en cuenta que:\r\nNo debe apliquar el desinfectante directamente al equipo o accesorios.\r\nNo debe dejar excesos de desinfectante en el equipo o accesorios.', 0, '2023-09-20 10:26:34', NULL),
(15, 'VENTILADOR MECÁNICO - SV600', 'El ventilador Mindray SV600 está diseñado para ser utilizado dentro de un centro sanitario, en cuidados intensivos o durante el traslado dentro de la instalación. Este equipo está concebido para proporcionar ayuda en la ventilación y respiración de pacientes adultos, pediátricos o recién nacidos.\r\n', 'Este ventilador solo debe ser usado por el personal médico autorizado. Antes de poner en marcha el sistema el operador debe verificar el buen estado de los accesorios y el equipo.\r\n', '--', '--', 'Aplique el desinfectante a usar de manera moderada a la toalla.\r\nPase la toalla por las superficies del equipo y accesorios.\r\n', 'Para evitar daños en el equipo al momendo de la desinfección tenga en cuenta que:\r\nNo debe apliquar el desinfectante directamente al equipo o accesorios.\r\nNo debe dejar excesos de desinfectante en el equipo o accesorios.', 0, '2023-09-20 10:28:06', NULL);

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `imagen_guia`
--

CREATE TABLE `imagen_guia` (
  `idimagen_guia` int(11) NOT NULL,
  `nombre_img` varchar(45) DEFAULT NULL,
  `descripcion` longtext DEFAULT NULL,
  `idguia` int(11) DEFAULT NULL,
  `seccion` varchar(45) DEFAULT NULL,
  `ubicacion` varchar(45) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `imagen_guia`
--

INSERT INTO `imagen_guia` (`idimagen_guia`, `nombre_img`, `descripcion`, `idguia`, `seccion`, `ubicacion`) VALUES
(1, 'G1.webp', NULL, 1, 'principal', NULL),
(2, 'G2.png', NULL, 2, 'principal', NULL),
(3, 'G3.png', NULL, 3, 'principal', NULL),
(4, 'G4.jpg', NULL, 4, 'principal', NULL),
(5, 'G5.jpg', NULL, 5, 'principal', NULL),
(6, 'G6.jpg', NULL, 6, 'principal', NULL),
(7, 'G7.png', NULL, 7, 'principal', NULL),
(8, 'G8.png', NULL, 8, 'principal', NULL),
(9, 'G9.png', NULL, 9, 'principal', NULL),
(10, 'G10.png', NULL, 10, 'principal', NULL),
(11, 'G11.jpeg', NULL, 11, 'principal', NULL),
(12, 'G12.png', NULL, 12, 'principal', NULL),
(13, 'G13.png', NULL, 13, 'principal', NULL),
(14, 'G15.png', NULL, 14, 'principal', NULL),
(15, 'G16.png', NULL, 15, 'principal', NULL),
(16, 'G1P1.png', '1 Pantalla.\r\n2 Teclas de navegación.\r\n3 Cancelar o retroceder.\r\n4 Iniciar infusión.\r\n5 Eliminar lo programado.\r\n6 Encendido y apagado.\r\n7 Indicadores de alimentación de la red eléctrica y estado de la batería.\r\n8 Palanca para abrir y cerrar la puerta.\r\n9 Menú.\r\n10 Silenciar alarmas.\r\n11 Pausar la infusión.\r\n12 Aceptar.\r\n', 1, 'partes', NULL),
(17, 'G2P1.png', '1 Selecciones de menú\r\n2 Botones de selección del menú\r\n3 Pantalla gráfica\r\n4 línea de estado\r\n5 Led de estado\r\n6 Ajustes de entrada\r\n7 Totales de salida\r\n8 Botón de encendido\r\n9 Estado de la batería\r\n10 Zona de almacenamiento de tapones de equipos de alimentos\r\n11 Puerta\r\n12 Mango integrado\r\n13 Punto de conexión de la abrazadera para palo gotero \r\n14 Puerto del adaptador de CA\r\n15 Puerto E/S en serie\r\n16 Compartimiento de la batería', 2, 'partes', NULL),
(18, 'G3P1.png', NULL, 3, 'partes', NULL),
(19, 'G3P2.png', '1 Pantalla de visualización.\r\n2 Indicador de alimentación de CA.\r\n3 Indicador de carga de batería.\r\n4 Indicador de estado (cruz roja).\r\n5 Indicador de estado (marca verde).\r\n6 Teclas de software.\r\n', 3, 'partes', NULL),
(20, 'G3P3.png', '1 Botón selección derivadas.\r\n2 Botón selección de ganancia.\r\n3 Botón para registrar.\r\n4 Botón para pausa de alarma.\r\n5 Botón Marcar evento.\r\n6 Botón Menú principal.\r\n7 Mando de navegación.\r\n', 3, 'partes', NULL),
(21, 'G3P4.png', '1 Mando de selección de modos.\n2 Botón Selec. energía.\n3 Botón Carga.\n4 Botón Descarga.\n', 3, 'partes', NULL),
(22, 'G3P5.png', '1 Botón Descarga.\n2 Botón Selec. energ.\n3 Indicador de descarga.\n4 Botón Carga.\n5 Botón Descarga.\n', 3, 'partes', NULL),
(23, 'G3P6.png', NULL, 3, 'partes', NULL),
(24, 'G4P1.png', 'A Botón de ON/OFF.\r\nB Selección de menús de la pantalla.\r\nC Teclas de manejo.\r\nD Seleccionar.\r\nE Cambio de página de la pantalla.\r\nF Impresión de la señal filtrada con la derivación II larga.\r\nG Impresión de la señal vista en la pantalla.\r\nH Volver al menú anterior.\r\nI Borrar caracteres.\r\nJ Detener la impresión.\r\nK Indicadores de estado de batería.\r\n', 4, 'partes', NULL),
(25, 'G4P2.png', 'Mantener el equipo conectado con el  cargador en el puerto A.\r\n', 4, 'partes', NULL),
(26, 'G5P1.png', '1 Puerta de tiras reactivas\r\n2 Pantalla táctil\r\n3 Botón ON/OFF', 5, 'partes', NULL),
(27, 'G5P2.png', '4 lector de código de barras\r\n5 Botón de reinicio\r\n6 Compartimiento para la batería\r\n7 Interfaz de infrarrojos \r\n8 Cubierta para la tarjeta RF\r\n', 5, 'partes', NULL),
(28, 'G5P3.png', '9 Estación base. \r\nPermite cargar la batería del equipo y la comunicación con el sistema de gestión de datos del hospital', 5, 'partes', NULL),
(29, 'G6P1.png', 'Cada vez que se manipule el equipo, se debe hacer desde la “manija”  y no  desde cualquier otra parte del mismo.\r\n', 6, 'partes', NULL),
(30, 'G6P2.png', '1 Botón de encendido.\r\n2 Disminuir iluminación.\r\n3 Aumentar iluminación.\r\n4 Indicador de fallos.\r\n5 Indicadores del nivel de iluminación.\r\n', 6, 'partes', NULL),
(31, 'G7P1.png', '1 Botón luz.\r\n2 Vaporizador.\r\n3 Cola de milano superior.\r\n4 Control O2 alternativo.\r\n5 Interruptor del sistema.\r\n6 Indicador de corriente de red.\r\n7 Aspirador integrado.\r\n8 Cola de milano inferior.\r\n9 Freno.\r\n10 Botón de purga de O2.\r\n11 Sistema de respiración avanzado.\r\n12 Control de flujo de O2 auxiliar.\r\n13 Pantalla de anestesia.\r\n', 7, 'partes', NULL),
(32, 'G7P2.png', '1 Interruptor de toma de corriente.\r\n2 Toma de corriente aislada.\r\n3 Conexión de vacío.\r\n4 Conexión de la botella de recogido.\r\n5 Horquilla de las botellas.\r\n6 AGSS (Sistema de evacuación de gases anestésicos).\r\n7 Espiga equipotencial.\r\n8 Conexión de entrada de corriente.\r\n9 Interruptor del sistema.\r\n10 Conexiones de las canalizaciones.\r\n', 7, 'partes', NULL),
(33, 'G7P3.png', '1 Válvula espiratoria.\r\n2 Válvula inspiratoria.\r\n3 Puerto inspiratorio.\r\n4 Puerto espiratorio.\r\n5 Canister.\r\n6 Palanca para retiro del canister.\r\n7 Tapón para comprobación de fugas.\r\n8 Puerto de bolsa manual.\r\n9 Apertura del sistema de respiración.\r\n10 Válvula limitadora de presión ajustable (APL).\r\n11 Conmutador Bolsa/Vent.\r\n12 Conjunto de concertina.\r\n', 7, 'partes', NULL),
(34, 'G7P4.png', '1 Simbolo de pausa de alarma.\r\n2 Mensajes de alarma.\r\n3 Ondas de los valores medidos.\r\n4 Campo de mensajes generales.\r\n5 Campo de valores medidos.\r\n6 Reloj.\r\n7 Teclas de función.\r\n8 Campos digitales.\r\n9 Modo de ventilación.\r\n10 Teclas rápidas del ventilador.\r\n11 Teclas rápidas de gas.\r\n12 Pantalla dividida.\r\n', 7, 'partes', NULL),
(35, 'G8P1.png', '1 Visor digital de gas fresco.\r\n2 Mando de control de gas fresco.\r\n3 Flujómetro de gas fresco total.\r\n4 Vaporizador.\r\n5 Regulador y control de aspiración.\r\n6 Interruptor de encendido/en espera.\r\n7 Freno de ruedas traseras.\r\n8 Freno central.\r\n9 Conexión de la manguera de la bolsa.\r\n10 Purga de O2.\r\n11 Puerta del sistema de respiración.\r\n12 Tapón para comprobación de fugas.\r\n13 Conmutador Bolsa/Vent.\r\n14 Válvula limitador de presión ajustable (APL).\r\n15 Conmutador de salida común de gases auxiliar (ACGO).\r\n16 Salida de O2 auxiliar.\r\n17 Flujómetro de O2 auxiliar.\r\n', 8, 'partes', NULL),
(36, 'G8P2.png', '1 Brazo de soporte de la bolsa.\r\n2 Guarda del sistema de respiración.\r\n3 Puerto de inspiración.\r\n4 Puerto de espiración.\r\n5 Recipiente del absorbedor.\r\n6 Asa de elevación del recipiente del absorbedor.\r\n7 Riel en cola de milano izquierda.\r\n8 Puerto del sistema de evacuación de gases anestésicos (AGSS).\r\n9 Puerto de retorno del gas de muestra.\r\n10 Módulo de gases.\r\n11 Trampa de aspiración.\r\n12 Conexión de aspiración.\r\n', 8, 'partes', NULL),
(37, 'G8P3.png', '1 Mando giratorio.\r\n2 Tecla de inicio.\r\n3 Tecla de bloqueo/desbloqueo de pantalla.\r\n4 Tecla iniciar/finalizar caso.\r\n5 Pantalla táctil.\r\n6 Tecla de pausa de audio durante 120 segundos.\r\n', 8, 'partes', NULL),
(38, 'G8P4.png', '1 Campo para visualizar ondas.\r\n2 Valores medidos.\r\n3 Teclas de función.\r\n4 Campos digitales.\r\n5 Teclas rápidas del ventilador.\r\n6 Valores de pantalla dividida.\r\n', 8, 'partes', NULL),
(39, 'G9P1.png', '1 Tablero.\r\n2 Cabecera.\r\n3 Semirrespaldo.\r\n4 Asiento.\r\n5 Mando de emergencia.\r\n6 Columna.\r\n7 Conexión del control.\r\n8 Mando a distancia.\r\n9 Perneras.\r\n', 9, 'partes', NULL),
(40, 'G9P2.png', '1 Fusible de las baterías.\r\n2 Puerto de alimentación AC.\r\n3 Toma equipotencial.\r\n', 9, 'partes', NULL),
(41, 'G9P3.png', '1 Trendelenburg.\r\n2 Subir.\r\n3 Inclinicación a la izquierda.\r\n4 Botón de validación del movimiento.\r\n5 Mover cabecero.\r\n6 Subir respaldo.\r\n7 Fijación al suelo (Frenos).\r\n8 Trrendelenburg invertida.\r\n9 Bajar.\r\n10 Inclincación a la derecha.\r\n11 Bluetooth.\r\n12 Detener movimientos.\r\n13 Mover perneras.\r\n14 Bajar respaldo.\r\n15 Desboquear ruedas.\r\n', 9, 'partes', NULL),
(42, 'G9P4.png', '1 Pantalla.\r\n2 Dirección de movimiento.\r\n3 Selección de sección del tablero (número 1 ítem I) a mover.\r\n4 Memoria de movimientos.\r\n5 Regreso a nivel horizontal e indicador de nivel.\r\n6 Detener la mesa.\r\n7 Bloqueo y desbloqueo de llantas con indicador de desbloqueo.\r\n8 Movimientos de la mesa.\r\n9 Colocación del paciente en la mesa e indicador.\r\n\r\n', 9, 'partes', NULL),
(43, 'G10P1.png', '1 Luz de alarma.\r\n2 Mango de transporte.\r\n3 Conectores de hemodinámica.\r\n4 Panel de teclas.\r\n5 Mando giratorio.\r\n', 10, 'partes', NULL),
(44, 'G10P2.png', '1 Botón para encendido y apagado.\r\n2 Indicador de conexión a alimentación AC.\r\n3 Indicador de estado de batería.\r\n4 Tecla de pausa de audio.\r\n5 Captura instantánea de datos medidos en ese momento.\r\n6 Tecla para inicio de medición de PANI.\r\n', 10, 'partes', NULL),
(45, 'G10P3.png', '1 Inicio.\r\n2 Menú del paciente.\r\n3 Tendencias.\r\n4 Iniciar registro de parámetros.\r\n5 Inicio del ciclo de toma de PANI.\r\n6 Poner a cero las presiones.\r\n7 Pausar el ciclo de PANI.\r\n8 Cambio de pantalla.\r\n9 Silenciar alarmas.\r\n10 Menú.\r\n', 10, 'partes', NULL),
(46, 'G10P4.png', '1 Conector de PI.\r\n2 Conector de temperatura.\r\n3 Conector de SpO2.\r\n4 Conector de ECG.\r\n5 Conector de PANI.\r\n', 10, 'partes', NULL),
(47, 'G11P1.png', '1 Luz de alarma.\r\n2 Indicador de alimentación de AC.\r\n3 Encendido y apagado del equipo.\r\n', 11, 'partes', NULL),
(48, 'G11P2.png', '1 Ranura para conectar módulos.\r\n2 Conectores para cable de red.\r\n', 11, 'partes', NULL),
(49, 'G11P3.png', '1 Encendido/apagado automático de PANI.\r\n2 Iniciar/cancelar PANI.\r\n3 Cero P2. \r\n4 Lengüeta.\r\n5 Conexión de PANI.\r\n6 Conexión de SpO2.\r\n7 Conexión Temp.\r\n8 Conexión PAI.\r\n9 Conexión PANI.\r\n10 Cero P1.\r\n', 11, 'partes', NULL),
(50, 'G12P1.png', '1 Luz de alarma.\r\n2 Pantalla de visualización.\r\n3 interruptor de encendido/apagado.\r\n4 Led de alimentación AC.\r\n5 Led de estado de batería.\r\n6 Silenciar todos los sonidos de alarma.\r\n7 Pausar o restaurar alarmas.\r\n8 Congelar/continuar ondas.\r\n9 Mando.\r\n10 Menú principal.\r\n11 Iniciar/detener los registros.\r\n12 Iniciar/detener toma de PANI.\r\n', 12, 'partes', NULL),
(51, 'G12P2.png', '1 Conector para el cable de GC.\r\n2 Salida de CO2.\r\n3 Ranura para colector CO2.\r\n4 Conector pra el cable de ECG.\r\n5 Conector para el cable SpO2.\r\n6 Conector para el manguito de PNI.\r\n7 Conector para la sonda de temperatura 1.\r\n8 Conector para la sonda de temperatura 2.\r\n9 Conector para el cable PI.\r\n', 12, 'partes', NULL),
(52, 'G13P1.png', '1 Silenciar alarmas.\r\n2 Ver o ajustar alarmas.\r\n3 Botón +/- para ajustar límites de alarmas o navegar por listas.\r\n4 Menú para ajustar Presión inicial, Volumen de alarma o pulso.\r\n5 Conector del SpO2.\r\n6 Conector de PANI.\r\n7 Botón papra inflar o para.\r\n8 Lugar donde se guarda la sonda de temperatura.\r\n9 Ajusta la toma de PANI automática o manual.\r\n10 Compartimento para guardar sonda de temperatura.\r\n11 Acceder al historial del paciente.\r\n12 Botón de imprimir.\r\n13 Encendido o apagado.\r\n14 Conecto de la sonda de temperatura.\r\n', 13, 'partes', NULL),
(53, 'G15P1.png', '1 Pantalla.\r\n2 Compartimento para módulo de vías áereas.\r\n3 Puerto inspiratorio.\r\n4 Conexión del nebulizador.\r\n5 Válvula espiratoria.\r\n6 Puerto de estacionamiento del circuito.\r\n7 Pestillo de la carcasa de la válvula espiratoria.\r\n8 Puerto de presión auxiliar.\r\n\r\n', 14, 'partes', NULL),
(54, 'G15P2.png', '1 Conector de cable AC.\r\n2 Interruptor de encendido/apagado del equipo.\r\n3 Conexión del compartimento para módulos.\r\n4 Filtro del ventilador de la pantalla.\r\n5 Conexión de suministro de Aire y Oxígeno.\r\n', 14, 'partes', NULL),
(55, 'G15P3.png', '1 Para conectar la valvula, coloque la lengüeta, marcado con el número 2 en la figura 1, en el surco, marcado con el número 1 en la figura 1, y presione la válvula desde el centro de la misma, hasta escuchar el Click indicando que queda asegurada.\r\nNota: No ubicar módulos en el costado se conecta la válvula expiratoria, como se evidencia en la figura 2.\r\n', 14, 'partes', NULL),
(56, 'G15P4.png', NULL, 14, 'partes', NULL),
(57, 'G15P5.png', '2 Para soltar la válvula, baje el seguro, señalado con el número 1 en la figura 3, para soltar la carcasa y retirarla del ventilador, teniendo cuidado con la lengüeta de la válvula.\r\n', 14, 'partes', NULL),
(58, 'G15P6.png', '1 Favoritos (acceso rápido a máximo 4 opciones).\r\n2 Estado del paciente (vista de la presión en vías aéreas del paciente).\r\n3 Navegación entre diferentes vistas.\r\n4 Información adicional.\r\n5 Alimentación de la red eléctrica.\r\n6 Puesta en espera.\r\n7 Teclas rápidas.\r\n8 Modo actual y ajustes de modo.\r\n9 Mensajes generales.\r\n10 Monitorización.\r\n11 Menú.\r\n12 Menú del paciente actual.\r\n13 Gestión de alarmas.\r\n14 Luz de alarma.\r\n', 14, 'partes', NULL),
(59, 'G15P7.png', '1 Indicador led de conexión a suministeléctrico.\r\n2 Tecla para pausar las alarmas por 2 minutos.\r\n3 Incrementar O2 durante la ventilación.\r\n4 Captura de pantalla.\r\n5 Bloquear o desbloquear el táctil de la pantalla.\r\n6 Tecla de inicio. \r\n7 Perilla de mando.\r\n', 14, 'partes', NULL),
(60, 'G16P1.png', '1 Monitor.\r\n2 Válvula de inspiración.\r\n3 Válvula de espiración.\r\n', 15, 'partes', NULL),
(61, 'G16P2.png', '1 Filtro espiratorio e inspiratorio.\r\n2 Colector de agua espiratorio e inspiratorio.\r\n3 Filtro HME.\r\n4 Gancho del brazo de apoyo.\r\n\r\nPaso a paso:\r\n1 Monte los filtros en los puertos inspiratorio y espiratorio.\r\n2 Conecte cada filtro a su colector de agua respectivo mediante un tubo y conecte el colector a cada extremo de la pieza en Y.\r\n3 Conecte la pieza en Y al HME para posteriormente conectar al paciente.\r\n4 Coloque los tubos del paciente en el gancho del brazo de apoyo.\r\n', 15, 'partes', NULL),
(62, 'G16P3.png', '1 Pantalla táctil.\r\n2 Luz indicadora de alarma.\r\n3 Mando de control.\r\n4 Tecla AUDIO PAUSADO de alarmas.\r\n5 Luz indicadora del estado de la batería y de alimentación AC.\r\n6 Interruptor de Encendido/Apagado del sistema.\r\n', 15, 'partes', NULL),
(63, 'G16P4.png', '1 Área de modo y de talla del paciente.\r\n2 Área de visualización de información.\r\n3 Área de íconos.\r\n4 Área de teclas funcionales.\r\n5 Modo de ventilación y área de ajuste de parámetros.\r\n6 Área de gráfico de tendencias/representación pulmonar dinámica/parámetros/ondas.\r\n', 15, 'partes', NULL),
(64, 'G1F1.png', 'Fig. 1. Dirección de flujo del sistema.\r\n', 1, 'funciones', NULL),
(65, 'G1F2.png', 'Fig. 2. Carga y descarga de la pinza.\r\n', 1, 'funciones', NULL),
(66, 'G1F3.png', 'Fig. 3. Instructivo de ajuste del sistema.\r\nNota:\r\nPara realizar la instalación el sistema debe estar prugado adecuadamente.\r\n1 Abra la puertas subiendo la palanca (número 8 del ítem I).\r\n2 Tenga en cuenta la dirección de flujo del sistema (Figura 1).\r\n3 Para acoplar el sistema primero debe cerrar la pinza.\r\n4 Iniciar introduciendo la pienza como muesta el numeral 1 de la figura 3.\r\n5 Tiemple delicadamente el sistema para acoplarlo de los extremos como muestra el numeral 2 de la figura 3.\r\n6 Termine de ajustar el sistema en como muestra el numeral 3 y 4 de la figura 3.\r\n\r\n', 1, 'funciones', NULL),
(67, 'G1F4.png', 'Fig.1. Instructivo de retiro del sistema.\r\n\r\n1 Presione el boton para detener la infusión (número 11 del ítem I).\r\n2 Presione el clip gris como muestra la figura 1.\r\n3 Primero retire el equipo de los extremos y siga retirando el equipo de cada enganche.\r\n4 Cierre la puerta, levantandola y empujando la palanca (número 8 del ítem I).\r\n\r\n', 1, 'funciones', NULL),
(68, 'G2F1.png', '1. Pulse ENCENDIDO en la esquina inferior derecha del panel de control \r\n2 Abra la puerta azul que delimita la zona de carga de equipos para bomba\r\n3 Para cargar el equipo para bomba siga la imagen relacionada', 2, 'funciones', NULL),
(69, 'G2F2.png', '4. Para cebar automáticamente la bomba siga la imagen relacionada \r\n', 2, 'funciones', NULL),
(70, 'G2F3.png', '5 utilice los botones de la parte izquierda del LCD para definir los parámetros de alimentación.\r\n6 Pulse EJECUTAR cuando este listo para comenzar \r\n', 2, 'funciones', NULL),
(71, 'G2F4.png', '7 Para detener la operación pulse PAUSA.', 2, 'funciones', NULL),
(72, 'G4P3.png', 'A Línea de información.\r\nB Hora.\r\nC Fecha.\r\nD Indicador de la calidad de la señal.\r\nE Indicador del estado de la batería.\r\nF Frecuencia cardiaca del paciente.\r\nG Versión del software.\r\nH Señal del paciente.\r\nI Opciones del menú.\r\n', 4, 'partes', NULL),
(73, 'G4F2.png', '1 Limpie y aplique  gel de ultrasonido donde se van a ubicar los electrodos sobre el paciente.\n2 Ponga los electrodos al paciente teniendo en cuenta el ítem IV. \n3 Encienda el equipo con el botón A del item I\n4 Espere a que la señal se ponga estable, verificando el indicador D del ítem III.\n5 Para eliminar el exceso de ruido de la señal, puede verificar el filtro que se esté usando en “más” de las opciones del menú del item III.\n6 Para imprimir la señal, verifique que el equipo cuente con papel y seleccione el modo de impresión que requiera según el ítem I.\n', 4, 'funciones', NULL),
(74, 'G4F3.png', '1 Abra la tapa de la impresora, deslizándola hacia afuera y  permitiendo su apertura.\r\n2 Coloque la cara con cuadrícula del papel frente al equipo, y a su vez con la marca negra en la esquina superior del equipo.', 4, 'funciones', NULL),
(75, 'G5F1.png', '1 En el menú principal pulse \"Test de paciente\"\r\n2 Introduzca el ID del paciente\r\n3 Confirme que el lote de chip de medicación coincida con las tiras reactivas de uso, en caso que no corresponda pulse X y seleccione de la lista, si no aparece, configure el lote \r\n4 Espere a que el medidor le indique colocar la tira, el medidos le indica la posición en la que debe ir la tira. \r\n5 Coloque la gota de muestra, una vez medidor lo solicite. Coloque la gota de la sangre en el extremo frontal, NO aplique la sangre en la parte superior de la tira.\r\n6 Una vez el medidor muestre los resultados, confirme el resultado y cuando esté en la pantalla principal retire la tira. ', 5, 'funciones', NULL),
(76, 'G5F2.png', NULL, 5, 'funciones', NULL),
(77, 'G5F3.png', 'TEST DE CONTROL\r\n1 En el menú principal pulse \"TEST DE CONTROL\" y seleccione el nivel a procesar, si el equipo requiere control para procesar aparecerá la palabra NECESARIO frente al nivel que lo requiera. ', 5, 'funciones', NULL),
(78, 'G5F4.png', '2 Confirme que el lote de control coincide, si no corresponde pulse X y seleccione de la lista, si no aparece, configure el lote', 5, 'funciones', NULL),
(79, 'G5F5.png', '3 Confirme que el lote del chip de medición coincide con las tiras reactivas en uso, si no corresponde pulse X y seleccione de la lista, si no aparece configure el lote', 5, 'funciones', NULL),
(80, 'G5F6.png', '4 Una vez el medidor le solicite la tira, realice el mismo procedimiento que cuando toma un tes de paciente', 5, 'funciones', NULL),
(81, 'G5F7.png', '5 Una vez el medidor muestre resultado, puede confirmar los rangos de los lotes pulsando RANGO, confirme el resultado y una vez esté en la pantalla principal retire la tira', 5, 'funciones', NULL),
(82, 'G6F1.png', 'Encender luz blanca\r\nSi la lámpara cialítica está apagada, presionar 1 vez el botón Power.\r\nEncender luz verde\r\nSi la lámpara cialítica está apagada, presionar 2 veces el botón Power.\r\n', 6, 'funciones', NULL),
(83, 'G10F1.png', '1 Ubique la sonda de temperatura en el paciente.\r\n2 Conecte la sonda a la interfaz de temperatura.\r\n3 Conecte la línea de temperatura al monitor en el conector 2 según el ítlem IV.\r\n', 10, 'funciones', NULL),
(84, 'G10F2.png', NULL, 10, 'funciones', NULL),
(85, 'G10F3.png', '1 Limpie y aplique gel en la zona donde van los electrodos.\r\n2 Ponga los electrodos al paciente teniendo en cuenta la figura 2 o la configuración que necesite. \r\n3 Conecte los latiguillos a la interfaz.\r\n4 Conecte la interfaz al monitor en el conector 4 del ítem IV.\r\n', 10, 'funciones', NULL),
(86, 'G10F4.png', '1 Conecte la interfaz al monitor en el conector 3 del ítem IV.\r\n2 Ubique el sensor en el dedo del paciente.\r\n3 Conecte el sensor a la interfaz.\r\n4 Espere a que el monitor adquiera la medición.\r\n\r\nNota: \r\n- Si el paciente tiene esmalte en las uñas debe retirarlo.\r\n- De no ser posible dubicar el sensor en los dedos de las manos del paciente, se puede ubicar en los dedos del pie o en el lóbulo de la oreja.\r\n- La medición se puede ver afectada por luces fluorecentes, movimiento del sensor, perfución periferica deficiente.\r\n', 10, 'funciones', NULL),
(87, 'G10F5.png', '1 Conecte la manguera al monitor  en el conector 5 según el ítem IV.\r\n2 Coloque el brazalete de PANI rodeando el brazo del paciente, verifique que la flecha  quede sobre la arteria braquial.\r\n3 Verifique que los tubos del manguito y la manguera no se encuentren retorcidos, oprimidos.\r\n4 Presione el boton para iniciar la medición de PANI (Número 6 del ítem II).\r\n', 10, 'funciones', NULL),
(88, 'G10F6.png', '1 Monitor de signos vitales.\r\n2 Bolsa de solución con infusor de presión.\r\n3 Configuración del transductor.\r\n4 Interfaz de PAI.\r\n\r\nPREPARACIÓN \r\n1 Prepare el transductor según instrucciones.\r\n2 Conecte el transductor de presión al cable.\r\n3 Conecte el cable del transductor al conector 1 según el item iv.\r\n4 Conecte el transductor a la línea del paciente.\r\n5 Abrir la llave de paso del trasductor\r\n6 Presionar “cero” en el monitor.\r\n7 Cerrar la llave de paso del trasductor\r\n', 10, 'funciones', NULL),
(89, 'G11F1.png', '1 Módulo de adquisición.\r\n2 Bolsa de solución con infusor de presión.\r\n3 Configuración del transductor.\r\n4 Interfaz de PAI.\r\n\r\nPREPARACIÓN\r\n\r\n1 Prepare el transductor según instrucciones.\r\n2 Conecte el transductor de presión al cable.\r\n3 Elimine el aire atrapado en la instalación del transductor.\r\n4 Conecte el cable del transductor al conector de presión invasiva del ítem IV.\r\n5 Conecte el transductor a la línea del paciente.\r\n', 11, 'funciones', NULL),
(90, 'G11F2.png', '1 Conecte la manguera al monitor según el ítem IV.\r\n2 Coloque el brazalete de PANI rodeando el brazo del paciente, verifique que la flecha  quede sobre la arteria braquial.\r\n3 Verifique que los tubos del manguito y la manguera no se encuentren estén retorcidos, oprimidos o estirados.\r\n4 Presione en la pantalla táctil el símbolo para iniciar la medición de PANI.\r\n', 11, 'funciones', NULL),
(91, 'G11F3.png', '1 Conecte la interfaz al monitor según el ítem IV.\r\n2 Ubique el sensor en el paciente.\r\n3 Conecte el sensor a la interfaz.\r\n4 Espere a que el monitor adquiera la medición.\r\nNota: \r\nSi el paciente tiene esmalte en las uñas debe retirarlo.\r\nDe no ser posible dubicar el sensor en los dedos de las manos del paciente, se puede ubicar en los dedos del pie o en el lóbulo de la oreja.\r\nLa mediciónse puede ver afectada por luces fluorecentes, luz solar directa, movimiento del sensor, perfución periferica deficiente o pérdida de pulso por paro cardiaco.\r\n', 11, 'funciones', NULL),
(92, 'G11F4.png', '1 Ubique la sonda de temperatura en el paciente.\r\n2 Conecte la sonda a la interfaz de temperatura.\r\n3 Conecte la línea de temperatura al monitor según el ítlem IV.\r\n', 11, 'funciones', NULL),
(93, 'G11F5.png', NULL, 11, 'funciones', NULL),
(94, 'G11F6.png', '1 Limpie la zona donde van los electrodos, Si es necesario, afeite los puntos donde se colocarán los electrodos.\r\n2 Aplique la gel de ultrasonido donde se van a ubicar los electrodos sobre el paciente.\r\n3 Ponga los electrodos al paciente teniendo en cuenta la figura 2. \r\n4 Conecte los latiguillos a la interfaz.\r\n5 Conecte la interfaz al monitor según el ítem IV.\r\n', 11, 'funciones', NULL),
(95, 'G12F1.png', '', 12, 'funciones', NULL),
(96, 'G12F2.png', '\r\n1 Prepare la piel del paciente:\r\n - Se debe elegir una zona lisa.\r\n - Debe estar afeitada la zona cutánea.\r\n - Eliminar las células muertas.\r\n - Limpiar con agua y jabón.\r\n2 Conecte los elementos de sujeción.\r\n3 Coloque los electrodos al paciente y al conector de ECG.\r\n\r\nMONITOREO DE SpO2\r\n\r\n1 Elimine el esmalte coloreado de donde se va a ubicar el sensor.\r\n2 Ubique el sensor.\r\n3 Conecte el sensor a la interfaz.\r\n4 Conecte la interfaz al equipo.\r\n\r\nMONITOREO DE PANI\r\n\r\n1 Ubique al paciente cómodamente sentado.\r\n2 Piernas descruzadas.\r\n3 Planta de los pies sobre el suelo.\r\n4 Espalda y brazos apoyados.\r\n5 Ubique el centro del manguito del brazalete a la altura de la aurícula derecha del corazón.\r\n\r\nMONITOREO DE TEMPERATURA\r\n\r\n1 Seleccione la sonda adecuada para el paciente.\r\n2 Conecte el sensor al conector del equipo.\r\n3 Conecte correctamente la sonda al paciente.\r\n4 compruebe que los ajustes de alarmas son los adecuados.\r\n\r\n\r\n\r\n\r\n', 12, 'funciones', NULL),
(97, 'G12F3.png', '1 Conecte el cable de presión al conector PI.\r\n2 Prepare la solución del purgado, purgue el sistema.\r\n3 Conecte la vía de presión al catéter del paciente.\r\n4 Coloque el transductor de forma que se encuentre al mismo nivel que el corazon del paciente.\r\n5 Seleccione la etiqueta apropiada.\r\n6 Establezca el valor del transductor en cero.\r\n7 Una vez finalizada la calibración a cero, cierre la llave de paso hacia el exterior y abra la llave de paso hacia el paciente.', 12, 'funciones', NULL),
(98, 'G13F1.png', '1 Conecte la manguera al monitor según el ítem I.\r\n2 Coloque el brazalete de PANI rodeando el brazo del paciente, verifique que la flecha  quede sobre la arteria braquial.\r\n3 Verifique que los tubos del manguito y la manguera no se encuentren estén retorcidos, oprimidos o estirados.\r\n4 Presione en la pantalla táctil el símbolo para iniciar la medición de PANI.\r\n', 13, 'funciones', NULL),
(99, 'G13F2.png', '1 Conecte la interfaz al monitor según el ítem I.\r\n2 Ubique el sensor en el paciente.\r\n3 Conecte el sensor a la interfaz.\r\n4 Espere a que el monitor adquiera la medición.\r\n\r\nNota: \r\nSi el paciente tiene esmalte en las uñas debe retirarlo.\r\nDe no ser posible dubicar el sensor en los dedos de las manos del paciente, se puede ubicar en los dedos del pie o en el lóbulo de la oreja.\r\nLa medición se puede ver afectada por luces fluorecentes, luz solar directa, movimiento del sensor, perfución periferica deficiente o pérdida de pulso por paro cardiaco.\r\n', 13, 'funciones', NULL),
(100, 'G13F3.png', '1 Ubique la sonda de temperatura en el paciente.\r\n2 Conecte la sonda a la interfaz de temperatura.\r\n3 Conecte la línea de temperatura al monitor según el ítlem IV.\r\n', 13, 'funciones', NULL),
(101, 'G15F1.png', '1 Conecte el filtro inspiratorio (1) del paciente.\r\n2 Conecte la rama inspiratoria (2) del circuito del paciente al filtro inspiratorio\r\n3 Conecte la rama espiratoria (4) del circuito del paciente al filtro de la válvula espiratoria (3).\r\n4 Conecte los accesorios necesarios para el uso de los módulos a usar (sensor D-lite).\r\n5 Conecte el filtro HME.\r\n6 Conecte el codo del circuito al HME.\r\n\r\nNota: Para desconectarlo sigua las mismas incrucciones en sentido inverso.\r\n\r\nEncendido y apagado\r\n\r\nEncendido:\r\n1 Conecte el ventilado a la toma AC.\r\n2 Pulse el interruptor de encendido/apagado (Número 2 Item II).\r\n3 Debe escuchar dos tonos acústicos distintos.\r\n4 La luz de alarma va a alumbrar Azul, Rojo y amarillo sucesivamente (Número 14 Item IV).\r\n\r\nApagado:\r\n1 Desconecte el paciente del circuito respiratorio.\r\n2 Seleccione En espera.\r\n3 Seleccione Pausar ventilación.\r\n4 Pulse el interruprto de encencido/apagado (Número 2 Item II).\r\n\r\nSeleccionar paciente\r\n\r\n1 Seleccione Nuevo paciente.\r\n2 Seleccione el tipo de paciente Adulto, Pediátrico o Neonatal, Género (masculino o femenino), Altura, Peso, Diámetro tubo,  seleccione el protocolo de tubo Endotraq., Traq. o  --.\r\n\r\n\r\n\r\n\r\n', 14, 'funciones', NULL),
(102, 'G15F2.png', '1 Desde En Espera, seleccione Compr. Sistema como se muestra en la figura 1.\r\n2 Conecte el circuito y todos los accesorios que va a usar.\r\n3 Ocluya la pieza en Y en el puerto de oclusión (Número 14 Ítem I).\r\n4 Seleccione iniciar ►.\r\n5 Seleccione el ícono de información, que aparece debajo de Comp. Sistema para ver el menú Detalles compr. sistema.\r\n6 Siga las instrucciones de la comprobación del sistema que aparecerán en la pantalla.\r\n7 Conforme avanza la comrpobación, cada ítem tendra una marca (✓en verde si es apto y x si no es apto) como se evidencia en la figura 2. Cuando falla una comprobación aparece un icono de Ayuda donde se encuentras unas posibles causas para resolver el problema. De seguir presentando inconvenientes comunicarse directamente con el área de Equipos Médicos.\r\n', 14, 'funciones', NULL),
(103, 'G15F3.png', 'Figura 2. Pantalla de detalles de la comprobación del sistema.\r\n', 14, 'funciones', NULL),
(104, 'G15F4.png', '1 Seleccione Modo actual.\r\n2 Seleccione el modo de ventilación deseado:\r\n\r\n- A/C VC: Asistda/Controlada por volumen.\r\n- A/C PC: Asistida/Controlada por presión.\r\n- A/C PRVC: Asistida /Controlada porvolumen regulada por presión.\r\n- SIMV VC: Ventilación intermitente sincronizada obligatoria controlada por volumen.\r\n- SIMV PC: Ventilación intermitente sincronizada obligatoria controlada por volumen.\r\n- BiLevel: Ventilación con presión BiLevel en vías aéreas.\r\n- APRV: Ventilación por liberación de presión en vías aéreas.\r\n- CPAP/PS: Presión positiva continua en vías aéreas / Presión de soporte.\r\n- SBT: Prueba de respiración espontánea.\r\n- VS: Soportado por volumen.\r\n- VNI: Ventilación no invasiva. \r\nTerapia de O2\r\n\r\nNota: Para poder visualizar todos los modos ventilatorios debe seleccionar la lista completa, como se muestra en la figura 1.\r\n\r\n3 Defina los parámetros necesarios para el modo de ventilación escogido y confirme.\r\n4 Para definir un modo reserva, seleccione Modo actual y posteriormente Ajustes del modo reserva.\r\n5 Defina los parámetros deseados para el modo reserva y confirme.\r\n6 Confirme todos los ajustes del modo de ventilación.\r\n', 14, 'funciones', NULL),
(105, 'G3P7.png', '1 Registrador.\r\n2 Conector de cable e ECG.\r\n3 Conector del sensor de SpO2.\r\n', 3, 'partes', NULL),
(106, NULL, 'DEA\r\nDebe utilizarse en pacientes que hayan sufrido un paro cardíaco y con una edad mínima de 8 años. El paciente debe estar:\r\nInconsciente\r\nSin respiración espontánea.\r\nSin pulso.\r\nNo debe utilizarse en pacientes que presenten uno o más de los siguientes signos:\r\nReceptividad\r\nRespiración espontánea\r\nPulso palpable\r\n\r\nDESFIBRILACIÓN MANUAL\r\nLa desfibrilación asíncrona es el tratamiento inicial para la fibrilación ventricular y la taquicardia ventricular en pacientes sin pulso e inconscientes.\r\nNo debe utilizarse en paciente que presenten uno o más de los siguientes signos:\r\nReceptividad\r\nRespiración espontánea\r\nPulso palpable\r\n\r\nESTIMULACIÓN NO INVASIVA\r\nLa terapia de estimulación no invasiva está indicada en pacientes con bradicardia asintomática. También puede resultar útil en pacientes con asistolia, si se realiza de manera precoz. \r\n\r\nMONITORIZACIÓN\r\nLos parámetros a medir en el desfibrilador son:\r\n\r\nECG:  Este parámeto se puede medir con latiguillos de 3 o 5 derivaciones, las palas externas o los electrodos multifuncional. Se tendrá registro de la curva de ECG y el valor de la frecuencia cardiaca.\r\nFrecuencia Respiratorio: Este parámetro se mide a través de los electrodos ubicados en el tórax, mostrando el registro de la curva de FR.\r\nFrecuencia cardiaca: Este parámetro se mide a través de la SpO2 y se muestra el registro numérico.\r\nSpO2: Este parámetro se mide a través del sensor de saturación. Para mostrar la curva pletismográfica y el % de oxigenación de la sangre del paciente.\r\n', 3, 'funciones', NULL),
(107, NULL, 'ENCENDIDO DEL EQUIPO\r\n\r\n1 Enchufar el cable de poder de la máquina a la red eléctrica. Verifique que el indicador de corriente de red se ilumine (Número 6 del ítem I)\r\n2 Comprobar que el sistema de respiración está conectado correctamente.\r\n3 Colocar el interruptor del sistema del sistema (Número 5 del ítem I) en posición de encendido.\r\n4 Realizar una prueba preoperatoria antes de cada caso del día.\r\n5 Realizar una comprobación completa antes del primer caso del día.\r\n\r\nAPAGADO DEL EQUIPO\r\n1 Dar por finalizado el caso en el sistema.\r\n2 Asegurarse que el vaporizador esté apagado.\r\n3 Colocar el interruptor del sistema del sistema (Número 5 del ítem I) en posición de apagado.\r\n4 Cierre todas las perillas de flujo de O2.\r\nNota:\r\nEl sistema debe realizar una comprobación automática de la alimentación cuando lleve 12 horas seguidas funcionando. Por lo que se debe reiniciar el sistema y realizar una Comprobación completa.\r\n\r\nCOMPROBACIÓN COMPLETA \r\n1 Ingrese en el menú Comprobación y seleccione Comprobación Completa, donde se realizaran.\r\n -Ventilación y gases.\r\n -Fugas en circuito.\r\n -Célula de O2 de circuito.\r\n2 Siga las instrucciones que el sistema le pide.\r\n3 Si falla una comprobación, verifique haber cumplido las instrucciones. Finalmente, comuníquese con el área de equipos médicos.\r\n4 Una vez finalizada y aprobada la comprobación completa, seleccione Iniciar caso.\r\n\r\nCONEXIÓN DEL CIRCUITO DEL PACIENTE \r\n1 Conecte un filtro al puerto espiratorio (Número 4 Ítem III).\r\n2 Conecte el circuito del paciente al puerto inspiratorio (Número 3 Ítem III) y al filtro del puerto espiratorio.\r\n3 Conecte un filtro al terminal del paciente del circuito.\r\n4 Conecte los demás accesorios que requiera, según el tipo de ventilación que necesite.\r\n\r\nPUESTA EN MARCHA\r\n1 Ajuste el conmutador Bolsa/Vent. en bolsa.\r\n2 Seleccione iniciar caso.\r\n3 Seleccione Valores pred determinad.\r\n4 Confirme o modifique los valores de Peso ideal, Edad, Alarmas de CO2 y Alarma de volumen apnea.\r\n5 Para cambiar el modo ventilación, seleccione Modo. Realice el cambio y ajuste los parámetros seleccionando la tecla rápida de ventilación o Más ajustes.\r\n6 Para cambiar los valores de gas o el tipo de circuito, seleccione Configurar gas y realice el cambio.\r\n7 En el menú Iniciar caso, seleccione Iniciar caso ahora.\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n', 7, 'funciones', NULL),
(108, NULL, 'ENCENDIDO DEL SISTEMA\r\n1 Enchufe el cable de alimentación a una toma corriente. Verificando que el indicador de conexión a la red eléctrica esté encendido.\r\n2 Compruebe que el sistema de respiración está conectado correctamente.\r\n3 Apriete el interruptor de encendido/en espera (Número 6 del Ítem I) durante 1 segundo para encender el sistema.\r\n4 Realice una Comprobación completa antes del primer caso del día.\r\n5 Lleve a cabo una comprobación preoperatoria antes de cada caso.\r\n\r\nAPAGADO DEL SISTEMA\r\n1 De por finalizado el caso.\r\n2 Presione y mantenga presionado el interruptor de encendido/en espera (Número 6 del Ítem) durante un segundo.\r\n3 Seleccione Confirmar o pulse el mando giratorio antes de 10 segundos para apagar el sistema. \r\nNota:\r\nEl sistema debe realizar una comprobación automática de la alimentación cuando lleve 12 horas seguidas funcionando. Por lo que se debe reiniciar el sistema y realizar una Comprobación completa.\r\n\r\nCOMPROBACIÓN COMPLETA\r\n\r\n1 En el menú Comprobación, seleccione Comprobación completa. \r\n2 Siga las instrucciones que aparecen en el monitor. Durante esta comprobación se realizaran las siguientes pruebas:\r\n - Fuga en ventilador\r\n - Fuga en vaporizador\r\n - Controles de gas\r\n - Fuga en circuito\r\n3 Una que realice la Comprob. completa, inicie un caso.\r\nNota: \r\nSi falla una comprobación, siga las instrucciones para realizar otra comprobación. De continuar la falla comuníquese con el área de servico técnico.\r\n\r\nCONEXIÓN DEL CIRCUITO DEL PACIENTE \r\n1 Conecte un filtro al puerto espiratorio (Número 4 Ítem II).\r\n2 Conecte el circuito del paciente al puerto inspiratorio (Número 3 Ítem II) y al filtro del puerto espiratorio.\r\n3 Conecte un filtro al terminal del paciente del circuito.\r\n4 Conecte los demás accesorios que requiera, según el tipo de ventilación que necesite.\r\n\r\nPUESTA EN MARCHA\r\n1 Ajuste el conmutador Bolsa/Vent. en bolsa.\r\n2 Seleccione iniciar caso.\r\n3 Seleccione Valores pred determinad.\r\n4 Confirme o modifique los valores de Peso ideal, Edad, Alarmas de CO2 y Alarma de volumen apnea.\r\n\r\n\r\n\r\n\r\n\r\n\r\n', 8, 'funciones', NULL),
(109, NULL, 'ACCIONAR DE LA MESA\r\nMando de emergencia:\r\nMantenga sostenido el botón de validación de movimiento (número 4 del ítem III) y oprima el movimiento deseado.\r\n\r\nMovimiento del tablero con mando a distancia:\r\n1 Seleccione la parte del tablero a mover con el botón número 3 del ítem IV.\r\n2 Seleccione la dirección del movimiento que quiere realizar con la parte del tablero con el botón 2 del ítem IV.\r\n\r\nMovimiento de la mesa con mando a distancia:\r\n1 Mantenga oprimido el movimiento que quiere realizar.\r\n', 9, 'funciones', NULL),
(110, NULL, 'ENCENDIDO DEL SISTEMA\r\n1 Conecte el ventilador a la toma de alimentación. Asegurandose que el indicador de alimentación externa esté encendida (Número 5 del Ítem III).\r\n2 Pulse la tecla de encendido (Número 6 del Ítem III).\r\n3 La luz indicadora de alarma parpadea en amarillo y rojo alternativamente, a continuación se lleva a cabo una autocomprobación automática del altavoz y el zumbador.\r\n4 Aparecerá la pantalla de inicio y la pantalla de comprobación del sistema.\r\n\r\nIniciar ventilación\r\n\r\nNota: Antes de inciar la ventilación del paciente verifique que la autocomprobación haya sido aprobada.\r\n\r\n1 Seleccione el paciente\r\nÚltimo paciente:\r\nDefina en el menú los partros necesarios.\r\nNuevo paciente:\r\nDefina en el menú los partros necesarios.\r\nSeleccione los ajustes el modo de ventilación deseado y los límites de alarma que requiera.\r\n2 Seleccione el tipo de ventilación NIV (no invasiva) o Invasiva:\r\n3 Seleccione el modo ventilatorio a usar:\r\nV-A/C: Asistida controlada por volumen.\r\nP-A/C: Asistida controlada por presión.\r\nV-SIMV:  Obligatoria intermitente sincronizada con el volumen.\r\nP-SIMV:  Obligatoria intermitente sincronizada con la presión.\r\nCPAP/PSV:  Ventilación con presión de soporte.\r\nPRVC: Ventilación por control de volumen regulada por presión.\r\nPRVC-SIMV: Control de volumen regulado por presión - Ventilación obligatoria intermitente sincronizada.\r\nDuoLevel: Ventilación de presión positiva de las vías respiratorias de doble nivel.\r\nAPRV: Ventilación con liberación de presión en las vías respiratorias.\r\nVS: Ventilación con volumen de soporte.\r\nAMV: Ventilación adaptativa de volumen por minuto.\r\nCPRV: Ventilación de reanimación cardiopulmonar.\r\n\r\n', 15, 'funciones', NULL);

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `guia`
--
ALTER TABLE `guia`
  ADD PRIMARY KEY (`id`);

--
-- Indices de la tabla `imagen_guia`
--
ALTER TABLE `imagen_guia`
  ADD PRIMARY KEY (`idimagen_guia`),
  ADD KEY `fk_guia_has_image` (`idguia`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `guia`
--
ALTER TABLE `guia`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=16;

--
-- AUTO_INCREMENT de la tabla `imagen_guia`
--
ALTER TABLE `imagen_guia`
  MODIFY `idimagen_guia` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=111;

--
-- Restricciones para tablas volcadas
--

--
-- Filtros para la tabla `imagen_guia`
--
ALTER TABLE `imagen_guia`
  ADD CONSTRAINT `fk_guia_has_image` FOREIGN KEY (`idguia`) REFERENCES `guia` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
